@Url = http://localhost:3000

### Crear rectángulo
POST {{Url}}/rectangulos
Content-Type: application/json

{
  "ancho": 30,
  "alto": 20
}

###

### Crear cuadrado
POST {{Url}}/rectangulos
Content-Type: application/json

{
  "ancho": 7,
  "alto": 7
}

###

### Ver todos los rectángulos
GET {{Url}}/rectangulos

###

### Modificar un rectángulo
PUT {{Url}}/rectangulos/6
Content-Type: application/json

{
  "ancho": 40,
  "alto": 20
}

###

### Eliminar un rectángulo
DELETE {{Url}}/rectangulos/5
